# Generated by Django 3.2.4 on 2021-06-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipdon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='category',
        ),
        migrations.AddField(
            model_name='contest',
            name='past',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contest',
            name='upcoming',
            field=models.BooleanField(default=True),
        ),
    ]
